org.gradle.jvmargs=-Xmx6G -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
systemProp.java.net.preferIPv4Stack=true

mod_version=1.3.3-port

minecraft_version=1.21.1
minecraft_range=[1.21.1,1.21.2)
neo_version=21.1.241
neo_range=[21.1.0,21.2.0)
loader_range=[4,)
parchment_minecraft_version=1.21.1
parchment_version=2024.11.17

mantle_version=1.12.1-port
mantle_range=[1.12.1-port,)
tconstruct_range=[3.12.1-port,)
jsonthings_version=0.13.7
jsonthings_range=[0.13.7,)
jei_version=19.39.0.368
jei_range=[19.0.0,20.0.0)
